stages:
  - build
  - test

build_backend:
  stage: build
  script:
    - cd backend
    - .\mvnw clean compile

test_backend:
  stage: test
  script:
    - cd backend
    - .\mvnw test

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build