stages:
  - build
  - test

# ----- BACKEND -----
build_backend:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17

  script:
    - cd backend
    - chmod +x mvnw
    - ./mvnw clean compile

test_backend:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17

  script:
    - cd backend
    - chmod +x mvnw
    - ./mvnw test

# ----- FRONTEND -----
build_frontend:
  stage: build
  image: node:20

  script:
    - cd frontend
    - npm install
    - npm run build